// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj8PvyU26goW9FrPhvsgXaDx-WHmPL868',
    appId: '1:79639413322:web:43d00b19de768436f4dcb3',
    messagingSenderId: '79639413322',
    projectId: 'zoom-clone-283db',
    authDomain: 'zoom-clone-283db.firebaseapp.com',
    storageBucket: 'zoom-clone-283db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDWxKK8PdMJckVj92Gv9CaCJifEyxK_Vs',
    appId: '1:79639413322:android:56aab71a409083cff4dcb3',
    messagingSenderId: '79639413322',
    projectId: 'zoom-clone-283db',
    storageBucket: 'zoom-clone-283db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB00uoUrZPCayX5vBEXaintevIV2f4o00g',
    appId: '1:79639413322:ios:52c19c1dadb887cff4dcb3',
    messagingSenderId: '79639413322',
    projectId: 'zoom-clone-283db',
    storageBucket: 'zoom-clone-283db.appspot.com',
    iosClientId: '79639413322-i5rvhfsbkc3gao18m1gnmt55qv5fu789.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomCloneFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB00uoUrZPCayX5vBEXaintevIV2f4o00g',
    appId: '1:79639413322:ios:52c19c1dadb887cff4dcb3',
    messagingSenderId: '79639413322',
    projectId: 'zoom-clone-283db',
    storageBucket: 'zoom-clone-283db.appspot.com',
    iosClientId: '79639413322-i5rvhfsbkc3gao18m1gnmt55qv5fu789.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomCloneFlutter',
  );
}
